# Generated by Django 4.2.8 on 2026-01-28 07:49

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='VitalSigns',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('time', models.TimeField()),
                ('systolic_bp', models.IntegerField(blank=True, help_text='mmHg', null=True)),
                ('diastolic_bp', models.IntegerField(blank=True, help_text='mmHg', null=True)),
                ('heart_rate_bpm', models.IntegerField(blank=True, help_text='beats per minute', null=True)),
                ('temperature_celsius', models.FloatField(blank=True, help_text='°C', null=True)),
                ('respiratory_rate', models.IntegerField(blank=True, help_text='breaths per minute', null=True)),
                ('oxygen_saturation', models.FloatField(blank=True, help_text='%', null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vital_signs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Vital Signs',
                'ordering': ['-date', '-time'],
            },
        ),
        migrations.CreateModel(
            name='BloodReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('hemoglobin_g_dl', models.FloatField(blank=True, help_text='g/dL', null=True)),
                ('hematocrit_percent', models.FloatField(blank=True, help_text='%', null=True)),
                ('wbc_k_ul', models.FloatField(blank=True, help_text='K/µL', null=True)),
                ('platelets_k_ul', models.FloatField(blank=True, help_text='K/µL', null=True)),
                ('glucose_mg_dl', models.FloatField(blank=True, help_text='mg/dL', null=True)),
                ('creatinine_mg_dl', models.FloatField(blank=True, help_text='mg/dL', null=True)),
                ('bun_mg_dl', models.FloatField(blank=True, help_text='mg/dL', null=True)),
                ('total_cholesterol_mg_dl', models.FloatField(blank=True, help_text='mg/dL', null=True)),
                ('ldl_cholesterol_mg_dl', models.FloatField(blank=True, help_text='mg/dL', null=True)),
                ('hdl_cholesterol_mg_dl', models.FloatField(blank=True, help_text='mg/dL', null=True)),
                ('triglycerides_mg_dl', models.FloatField(blank=True, help_text='mg/dL', null=True)),
                ('ast_u_l', models.FloatField(blank=True, help_text='U/L', null=True)),
                ('alt_u_l', models.FloatField(blank=True, help_text='U/L', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blood_reports', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='HealthMetric',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('metric_type', models.CharField(choices=[('weight', 'Weight'), ('height', 'Height'), ('sleep', 'Sleep Hours'), ('exercise', 'Exercise Minutes'), ('water_intake', 'Water Intake (ml)'), ('mood', 'Mood Score'), ('stress', 'Stress Level')], max_length=50)),
                ('value', models.FloatField()),
                ('date', models.DateField()),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='health_metrics', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-date'],
                'unique_together': {('user', 'metric_type', 'date')},
            },
        ),
    ]
