# Generated by Django 4.2.8 on 2026-02-08 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('health_metrics', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='healthmetric',
            name='goal_date',
            field=models.DateField(blank=True, help_text='Target date to achieve goal', null=True),
        ),
        migrations.AddField(
            model_name='healthmetric',
            name='target_value',
            field=models.FloatField(blank=True, help_text='Target goal value', null=True),
        ),
    ]
